                    编程常见英语词汇
2014年7月23日星期三
1：subscript                下标
2：warning                  警告
3：error                    错误
4：syntax                   语法
5：indirection              间接的
6：direct                   直接的
7：differ                   不同
8：level                    水平，使同等
9：void                     空的，无效的，空虚的
10：int(integer)            整数
11：long                    长的
12：double                  双倍，双精度型
13：short                   短的
14：char                    字符
15：include                 包含，包括
16：stream                  河流，连续，流
17：string                  字符串，绳子
18：const                   常数，不变的
19：public                  公共的，公众的
20：private                 私有的，士兵的，平民的
21：main                    主要的
22：struct                   结构体
23：class                    种类，类
24：function                 函数，功能
25：non                      非，不
26：interactive              互动，交互式的
27：version                  版本
28：argument                 参数
29：reset                    重置
30：restore                  恢复
31：value                    值
32：contents                 内容
33：namespace                命名空间
34：item                     项目
35：array                    队列，数组
36：elements                 元素
37：compute                  计算，估算，推断
38：extern                   外来的
39：while                    在….期间
40：do                       做，干
41：for                      为了，倾向
42：case                     情况，判例
43：switch                   开关，转换
44：continue                 继续
45：break                    突变，打破
46：return                   返回
47：clear                    除去，扫除，明确的
48：file                     文件
49：float                    浮点，浮动
50：pointer                  指针
51：template                 模板
52：type                     类型
53：primer                   启蒙读本，入门书
54：plus                     加上
55：edition                  版本，版次
56：new                      新的
57：delete                   删除
58：abstract                 抽象的，理论上，摘要的
59：data                     数据
60：linux                    一种操作系统
61：standard                 标准
62：program                  程序
63：software                 软件
64：hardware                 硬件
65：language                 语言
66：object                   对象，反对不赞成
67：code                     代码，密码，编码
68：auto                     汽车，自动变量
69：static                   静态的，精止的
70：visual                   可视化的
71：source                   根源，本源，源头
72：integrate                使整合
73：development              开发区，发展
74：enviorment               环境 
   【IDE，集成开发环境】
75：compile                  编译，汇编
76：digital                  数据的，数字的
77：startup                  启动
78：insert                   插入，嵌入
79：precious                 珍贵的
80：sign                     符号，记号
81：unsign                   无符号
82：window                   窗口
83：application              应用
84：project                  项目，计划，工程
85：console                  控制台
86：build                    建立
87：make                     生成
88：link                     链接，关联
89：execute                  生成
90：run                      运行
91：debug                    调试
92：getchar                  获取字符
93：printf                   打印函数
94：scanf                    输入函数
95：buffer                   缓冲区
96：statement                声明，表现
97：definit                  定义
98：declare                  声明
99：heading                  标题，头部
100：terminator              终止符，终结者
101：list                    列表，清单
102：parameter               参数
103：original                原始的，原型
104：style                   风格，样式
105：explicit                明确的
106：comment                 注释
107：preprocess              预处理【pre 预】
108：directive                指令
109：raw                      原，生的
110：invalid                  无效的
111：carriage                 运输，运送
112：complete                 完整
113：union                    联盟
114：enum                     枚举
115：default                  缺省，默认，未履行
116：register                 寄存器，登记，注册
117：volatile                 不稳定的，易变的
118：typedef                  类型定义
119：if                       如果，条件，假想
120：else                     其他的，别的
121：goto                     转到
122：bool                     布尔
123：define                   定义
124：readonly                 只读
125：line                     线路，线
126：design                   设计


2014年7月23日星期四
127：invoking                  调用
128：initialized               已初始化的
128：modifier                  调节器
129：enclosing                 封闭的
130：specifies                 指定
131：conversion                转换，兑换
132：illegal                   不合法的
133：direction                 方向，指挥，命令
134：document                  文档
135：administrator             管理员
136：admini                    管理
137：Configuration             配置，组合，排列
138：this                      这事，这人，这，本身
139：precision                 精度
140：flag                      标示，旗帜
141：format                    格式，板式，模式
142：create                    创建
143：protect                   保护，保卫
144：constructor               构造器
145：swap                      互换
146：show                      显示
147：display                   展览，陈列，显示
148：print                     打印
149：address                   地址
150：caculate                  计算
151：load                      加载，装载
152：finance                   财政，金融，财务
153：charge                    费用，索价
154：balance                   均衡，权衡
155：withdraw                  撤退，退出
156：cancel                    取消
157：account                   账户，账目，存款
158：count                     计算，计数
159：exceed                    领先，超过
160：bank                      银行
161：advance                   提前，预付，借款
162：client                    客户端，顾客
163：server                    服务器
164：number                    数目
165：loan                      贷款
166：owed                      欠
167：example                   范例
168：temp                      临时
169：copy                      复制，模仿
170：rate                      比率
171：view                      视图，看
172：work                      操作
173：method                    方法
174：name                      名称
175：company                   公司，伙伴，陪同
176：reference                 参考，引用
177：limit                     限制，极限
178：enter                     进入，开始
179：screen                    屏幕，显示器
180：backspace                 退格
181：index                     索引
182：caps                      大写字母
183：lock                      锁定
184：shift                     位移，换挡
185：control                   控制
186：accelerate                加速
187：system                    系统，制度，身体
188：scroll                    滚动
189：home                      家，主键
190：page页  pageup上一页  pagedown下一页
191：end                       终止
192：mouse                     鼠标
193：keyboard                  键盘
194：memory                    内存
195：free                      免费，释放
196：bind                      捆绑，联编
197：dynamic                   动态
 【static binding】静态联编
 【dynamic binding】动态联编
198：virtual                   虚拟的
199：employee                  雇员
200：base                      基地，基
201：area                      范围
202：derived                   衍生，派生
203：vector                    矢量
204：container                 容器
205：friend                    朋友，友
206：operator                  运算符
207：cast                      铸造
208：present                   目前，当前
209：represent                 代表，象征
210：brand                     品牌，牌子
211：size                      大小
212：length                    长度
213：score                     得分
214：express                   表示
215：impression                印象，影响
216：average                   平均，典型的
217：sum                       总和
218：total                     总计
219：edit                      编辑
220：empty                     空的
221：check                     检查，核对
222：choose                    挑选，选择
223：target                    目标
224：attempt                   企图，攻击
225：attack                    攻击，侵袭
226：intelligence              智能
227：share                     共享，分享
228：assignment                赋值
229：hacker                    黑客
230：viruses                   病毒
231：unique                    独特
232：push                      推，压
233：heap                      堆积，堆
234：sort                      排序
235：begin                     开始
236：erase                     擦除
237：gain                      获得，增益
238：keyword                   关键字
239：follow                    跟随，继承
240：input                     输入
241：output                    输出
242：state                     状态，声明
243：write                     写
244：read                      读
245：put                       表达
246：flush                     刷新
247：field                     场地
248：internal                  内部
249：right                     右
250：left                      左
251：fixed                     固定的
252：math                      数学
253：stack                     栈
254：handicap                  障碍
255：passed                    通过
256：solicit                   征求
257：overload                  过载
258：acceptable                可接受的
259：take                      带走
260：stock                     股票
261：log                       日志
262：profile                   简介
263：analysis                  分析
264：option                    选项
265：configure                 配置，设定
266：tool                      工具
267：package                   包
268：manage                    管理
269：current                   当前，现在
270：login                     登录，注册
271：logout                    退出，注销
272：update                    更新
273：diff                      差异
274：remove                    去除，拆下
275：commit                    提交
276：add                       添加，加法
277：open                      正常开放   
278：close                     关闭
279：tip                       窍门，小费
280：null                      零值，空
281：browser                   浏览器
282：replace                   更换
283：paste                     粘贴
284：collapse                  崩溃，瓦解
285：save                      保存
286：exit                      出口，退出，离开
287：history                   历史
288：release                   释放
289：resource                  资源，源
290：untitled                  无题
291：path                      路径






2014年7月25日星期五
292：button                  按钮，纽扣
293：district                区域
294：re                      重新
295：cannot                  不能
296：abort                   中止
297：watch                   监视，注意，手表
298：execution               执行
299：process                 过程，处理
300：desktop                 桌面
301：skip                    跳过
302：instruction             指令
303：command                 指令，控制，指挥
304：translate               翻译，转化
305：disk                    磁盘
306：variable                变量
307：qualified               合格，胜任
308：previous                先前的
309：senior                  高级
310：primary                 低级，原始
311：script                  脚本
312：excel                   优于，擅长
313：power                   能量，权力
314：engine                  引擎
315：android                 安卓
316：swift                   迅速的，敏捷的
317：message                 消息
318：permissive              自由的，宽大的
319：recipe                  处方，秘诀
320：notation                记号，标记法

